---
- name: Run system update
  hosts: all
  tasks:
    - name: Apt update and upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day.
        autoclean: yes
        autoremove: yes

